import { useMemo, useState } from 'react';
import { evidenceRows, sourceLines } from './evidence-model';
import type { EvidencePost, EvidenceTranscript, EvidenceBlock } from './evidence-model';
import diagnosis from './thais-diagnosis.md?raw';
import structures from './thais-structures.md?raw';

export function EvidenceMemory({ posts, transcripts, blocks, onReference }: { posts: EvidencePost[]; transcripts: EvidenceTranscript[]; blocks: EvidenceBlock[]; onReference: (id: string) => void }) {
  const [view, setView] = useState('dados');
  const [filter, setFilter] = useState('all');
  const [selected, setSelected] = useState('DcUjm2eyjbC');
  const [doc, setDoc] = useState('diagnosis');
  const rows = useMemo(() => evidenceRows(posts, transcripts, blocks), [posts, transcripts, blocks]);
  const active = rows.find(r => r.post.id === selected) || rows[0];
  const speech = rows.filter(r => r.speech).length;
  const missing = rows.filter(r => !r.post.media_file).length;
  const divergence = rows.reduce((sum,r) => sum+r.mismatches.length,0);
  const filtered = rows.filter(r => filter === 'all' || (filter === 'speech' ? r.speech : filter === 'missing' ? !r.post.media_file : r.mismatches.length > 0));
  const button = 'rounded-lg border border-[#E3E1DA] px-3 py-2 text-sm hover:bg-[#F7F5F0]';
  const exportFile = (name: string, content: string, type = 'text/markdown;charset=utf-8') => {
    const url = URL.createObjectURL(new Blob([content], {type})); const a=document.createElement('a'); a.href=url; a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  return <section className="space-y-5 text-[#16231D]">
    <header className="rounded-xl border border-[#E3E1DA] bg-white p-5"><p className="text-xs tracking-widest text-[#66736B]">MEMÓRIA / FONTES DA CLIENTE</p><h2 className="mt-2 text-2xl font-semibold">Entender antes de escrever.</h2><p className="mt-2 text-sm text-[#66736B]">Copies publicadas são referências editoriais. Resultado comercial exige evidência própria. Dados abaixo vêm do acervo deste projeto.</p></header>
    <nav aria-label="Áreas da memória" className="flex flex-wrap gap-2">{[['dados','Dados'],['copy','Copywriting · referências'],['graph','Mapa de evidências'],['docs','Documentos']].map(([id,label])=><button key={id} className={`${button} ${view===id?'bg-[#19382B] text-white':''}`} aria-pressed={view===id} onClick={()=>setView(id)}>{label}</button>)}</nav>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[[posts.length,'Posts no acervo'],[speech,'Transcrições com fala'],[missing,'Sem mídia'],[divergence,'Blocos a conferir']].map(([n,label])=><article key={label} className="rounded-xl border border-[#E3E1DA] bg-white p-4"><strong className="text-2xl">{n}</strong><p className="mt-1 text-xs text-[#66736B]">{label}</p></article>)}</div>
    {view==='dados'&&<div className="space-y-3"><div className="flex flex-wrap gap-2"><label className="text-sm">Filtrar fontes <select className={button} value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Todas</option><option value="speech">Com fala útil</option><option value="missing">Sem mídia</option><option value="divergence">Blocos divergentes</option></select></label><button className={button} onClick={()=>exportFile('thais-acervo.json',JSON.stringify(rows,null,2),'application/json')}>Exportar JSON</button><button className={button} onClick={()=>{const cell=(x:unknown)=>`"${String(x??'').replace(/"/g,'""')}"`;const csv=[['post_id','canal','audio','plays','blocos_divergentes','fonte'],...rows.map(r=>[r.post.id,r.sourceKind,r.audioLabel,r.post.metrics?.plays??'',r.mismatches.length,r.post.source_url])].map(row=>row.map(cell).join(',')).join('\r\n');exportFile('thais-acervo.csv','\uFEFF'+csv,'text/csv;charset=utf-8');}}>Exportar CSV</button></div><div className="overflow-x-auto rounded-xl border border-[#E3E1DA] bg-white"><table className="w-full text-left text-sm"><thead><tr>{['Publicação','Canal disponível','Áudio','Plays registrados','Revisão'].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.post.id} className="border-t border-[#E3E1DA]"><td className="max-w-xs p-3"><button className="text-left underline" onClick={()=>{setSelected(r.post.id);setView('copy');}}>{r.post.caption.slice(0,85)||r.post.id}</button><p className="mt-1 text-xs text-[#66736B]">{r.post.id}</p></td><td className="p-3">{r.sourceKind}</td><td className="p-3">{r.audioLabel}</td><td className="p-3">{r.post.metrics?.plays != null ? Number(r.post.metrics.plays).toLocaleString('pt-BR') : 'Não informado'}</td><td className="p-3">{r.mismatches.length ? `${r.mismatches.length} divergência(s)`:'Sem divergência literal detectada'}</td></tr>)}</tbody></table></div><p className="text-xs text-[#66736B]">Plays não são pessoas únicas ou vendas. Ausência de divergência automática não significa aprovação humana. O acervo não representa todo o perfil.</p></div>}
    {view==='copy'&&active&&<div className="space-y-4"><label className="block text-sm">Referência publicada<select className={`${button} mt-2 w-full bg-white`} value={active.post.id} onChange={e=>setSelected(e.target.value)}>{rows.map(r=><option key={r.post.id} value={r.post.id}>{r.post.caption.slice(0,85)} · {r.sourceKind}</option>)}</select></label><div className="flex flex-wrap gap-2"><span className={button}>{active.sourceKind}</span><a className={button} href={active.post.source_url} target="_blank" rel="noreferrer">Abrir fonte</a><button className={`${button} bg-[#19382B] text-white`} onClick={()=>onReference(active.post.id)}>Usar como referência de 10 copies</button></div><p className="text-sm text-[#66736B]">O texto é preservado da fonte local. Os rótulos abaixo são uma leitura editorial por regras, não validação de performance. Transcrições ASR podem exigir revisão do áudio.</p><div className="grid gap-3 md:grid-cols-2">{sourceLines(active.source).map((line,i)=><article key={i} className="rounded-xl border border-[#E3E1DA] bg-white p-4"><span className="text-xs font-semibold text-[#66736B]">{String(i+1).padStart(2,'0')} · {line.role}</span><p className="mt-2 whitespace-pre-wrap">{line.text}</p></article>)}</div>{active.mismatches.length>0&&<details className="rounded-xl border border-amber-300 bg-amber-50 p-4"><summary className="cursor-pointer font-semibold">{active.mismatches.length} bloco(s) antigo(s) não coincidem literalmente com a fonte</summary><p className="my-2 text-sm">Podem conter paráfrase, cortes ou acréscimos. Foram preservados para revisão; não são usados aqui como citação literal.</p>{active.mismatches.map((b,i)=><p className="my-2 text-sm" key={b.id||i}>{b.role}: {b.literal_text}</p>)}</details>}</div>}
    {view==='graph'&&<div className="rounded-xl border border-[#E3E1DA] bg-white p-5"><h3 className="font-semibold">Cobertura das fontes</h3><p className="my-3 text-sm text-[#66736B]">Post publicado → mídia disponível → fala útil → análise → nova copy. As barras medem disponibilidade; não representam conversão.</p>{[[posts.length,'Posts'],[posts.filter(p=>p.media_file).length,'Mídias'],[speech,'Falas úteis']].map(([n,label])=><div className="my-4" key={label}><p className="mb-1 text-sm">{label}: {n}</p><div className="h-5 rounded bg-[#F7F5F0]"><div className="h-5 rounded bg-[#19382B]" style={{width:`${posts.length?Number(n)/posts.length*100:0}%`}}/></div></div>)}<p className="text-sm">Amostra oral pequena: use legendas como legendas e amplie a mídia antes de afirmar um padrão geral de fala.</p></div>}
    {view==='docs'&&<div className="space-y-3"><div className="flex flex-wrap gap-2"><button className={button} onClick={()=>setDoc('diagnosis')}>Diagnóstico da cliente e operação</button><button className={button} onClick={()=>setDoc('structures')}>Estruturas de copy</button><button className={button} onClick={()=>exportFile(`thais-${doc}.md`,doc==='diagnosis'?diagnosis:structures)}>Baixar Markdown</button></div><article className="whitespace-pre-wrap rounded-xl border border-[#E3E1DA] bg-white p-5 text-sm leading-7">{doc==='diagnosis'?diagnosis:structures}</article><p className="text-xs text-[#66736B]">Análise editorial de 08/09/2026; snapshot histórico. As tabelas de Dados acima refletem o acervo carregado agora.</p></div>}
  </section>;
}
