import React, { useEffect, useState } from 'react';
import { BookOpen, Database, ExternalLink, FileText, GitBranch, Mic, Play, ShieldCheck } from 'lucide-react';

type Section = 'overview' | 'references' | 'evidence' | 'documents';
const references = [
  { id: 'DcUjm2eyjbC', title: 'Música e desafio participativo', channel: 'Legenda publicada', cta: 'QUERO', text: 'Música → experiência prazerosa → desafio → aula → palavra-chave.', note: 'Referência principal. O áudio é música; legenda não é fala.', url: 'https://www.instagram.com/p/DcUjm2eyjbC/' },
  { id: 'Dce8x59SSP2', title: 'Descoberta do canal', channel: 'Fala transcrita', cta: 'ACESSO', text: 'Descoberta → benefício alegado → iniciante → convite → acesso.', note: 'Fala útil; alegações de resultado não devem ser herdadas.', url: 'https://www.instagram.com/p/Dce8x59SSP2/' },
  { id: 'Dcv2Yt4RBmX', title: 'História de rotina e nutrição', channel: 'Fala transcrita', cta: 'VERÃO', text: 'Expectativa → vulnerabilidade → processo → aprendizado → convite.', note: 'Estrutura longa; usar um conflito em vídeos curtos.', url: 'https://www.instagram.com/p/Dcv2Yt4RBmX/' },
  { id: 'DauwjqVBoHh', title: 'Baixo impacto e aula', channel: 'Legenda publicada', cta: 'MUNDOFIT', text: 'Desejo → formato da atividade → acesso → palavra-chave.', note: 'Sem fala útil confirmada e sem prova de compras.', url: 'https://www.instagram.com/p/DauwjqVBoHh/' },
];

export const ProfileTab: React.FC<{ onUseReference: () => void }> = ({ onUseReference }) => {
  const [section, setSection] = useState<Section>('overview');
  const [coverage, setCoverage] = useState({ posts: 15, transcripts: 15, media: 6, useful_speech: 2 });
  useEffect(() => {
    fetch('/api/profile/memory', { cache: 'no-store' })
      .then(response => response.ok ? response.json() : Promise.reject())
      .then(data => data?.coverage && setCoverage(data.coverage))
      .catch(() => undefined);
  }, []);
  const useReference = (item: typeof references[number]) => {
    localStorage.setItem('tg_esteira_theme', `${item.id} — ${item.title} — CTA ${item.cta}`);
    onUseReference();
  };
  return <div className="mx-auto max-w-6xl space-y-5">
    <header className="rounded-xl border border-[#dce1e3] bg-white p-6 shadow-sm"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-brand-gold">Perfil da cliente</p><h1 className="mt-2 text-2xl font-bold text-brand-forest">Thaix Santiago</h1><p className="mt-2 max-w-3xl text-sm text-[#5e727c]">Memória editorial baseada no acervo disponível. Fonte publicada, referência criativa e resultado comercial permanecem separados.</p></header>
    <nav className="flex flex-wrap gap-2" aria-label="Seções do perfil">{([['overview','Visão geral',BookOpen],['references','Referências',FileText],['evidence','Evidências',GitBranch],['documents','Documentos',Database]] as const).map(([id,label,Icon]) => <button key={id} type="button" onClick={() => setSection(id)} className={`inline-flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold ${section === id ? 'border-brand-forest bg-brand-forest text-white' : 'border-[#dce1e3] bg-white text-brand-forest'}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
    {section === 'overview' && <><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[[coverage.posts,'posts no acervo'],[coverage.transcripts,'registros de transcrição'],[coverage.media,'mídias disponíveis'],[coverage.useful_speech,'falas úteis confirmadas']].map(([value,label]) => <article key={label} className="rounded-xl border border-[#dce1e3] bg-white p-4"><strong className="text-2xl text-brand-forest">{value}</strong><p className="mt-1 text-xs text-[#5e727c]">{label}</p></article>)}</div><article className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="flex items-center gap-2 font-bold text-brand-forest"><ShieldCheck className="h-5 w-5" />Regra de confiança</h2><p className="mt-2 text-sm leading-6 text-[#43565f]">Plays e comentários descrevem publicações; não provam vendas. Legenda não é fala. Novas copies começam como rascunho e só viram referência aprovada após revisão humana.</p></article></>}
    {section === 'references' && <div className="grid gap-4 md:grid-cols-2">{references.map(item => <article key={item.id} className="rounded-xl border border-[#dce1e3] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-wide text-brand-gold">{item.channel}</p><h2 className="mt-1 font-bold text-brand-forest">{item.title}</h2></div>{item.channel.startsWith('Fala') ? <Mic className="h-5 w-5 text-brand-gold" /> : <FileText className="h-5 w-5 text-brand-gold" />}</div><p className="mt-3 text-sm leading-6 text-[#43565f]">{item.text}</p><p className="mt-3 rounded-lg bg-[#f6f7f7] p-3 text-xs text-[#5e727c]">{item.note}</p><div className="mt-4 flex flex-wrap gap-2"><a href={item.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-lg border border-[#dce1e3] px-3 py-2 text-xs font-semibold text-brand-forest">Abrir fonte <ExternalLink className="h-3 w-3" /></a><button type="button" onClick={() => useReference(item)} className="inline-flex items-center gap-1 rounded-lg bg-brand-forest px-3 py-2 text-xs font-semibold text-white">Usar no Simples <Play className="h-3 w-3" /></button></div></article>)}</div>}
    {section === 'evidence' && <article className="rounded-xl border border-[#dce1e3] bg-white p-6"><h2 className="font-bold text-brand-forest">Cobertura do acervo</h2><p className="mt-2 text-sm text-[#5e727c]">{coverage.posts} posts → {coverage.media} mídias → {coverage.useful_speech} falas úteis → análise editorial → nova copy em rascunho.</p>{[['Posts',coverage.posts],['Mídias',coverage.media],['Falas úteis',coverage.useful_speech]].map(([label,value]) => <div className="mt-4" key={label}><div className="mb-1 flex justify-between text-xs"><span>{label}</span><strong>{value}</strong></div><div className="h-3 rounded-full bg-[#edf0ef]"><div className="h-3 rounded-full bg-brand-forest" style={{width:`${coverage.posts ? Number(value)/coverage.posts*100 : 0}%`}} /></div></div>)}<p className="mt-5 text-xs text-[#5e727c]">7 blocos antigos têm divergência literal e precisam de revisão. O acervo é uma amostra, não representa todo o perfil.</p></article>}
    {section === 'documents' && <div className="grid gap-4 md:grid-cols-2"><Doc title="Diagnóstico" text="Inventário das fontes, limites da reunião corrompida, cobertura real e política para não transformar interpretações em fatos." href="/docs/thais-copy-intel/01-DIAGNOSTICO-E-ENTREGA.md" /><Doc title="Análise estrutural" text="Quatro referências com canal, estrutura reutilizável, riscos de alegação e regras para o primeiro lote." href="/docs/thais-copy-intel/02-ANALISE-ESTRUTURAL.md" /></div>}
  </div>;
};

const Doc = ({ title, text, href }: { title: string; text: string; href: string }) => <article className="rounded-xl border border-[#dce1e3] bg-white p-5"><h2 className="font-bold text-brand-forest">{title}</h2><p className="mt-2 text-sm leading-6 text-[#5e727c]">{text}</p><a className="mt-4 inline-block text-xs font-bold text-brand-gold underline" href={href} target="_blank">Abrir documento</a></article>;
